services:
  ollama:
    image: ollama/ollama:0.3.12
    ports:
      - 11434:11434
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    volumes:
      - ./install-ollama-models-small.sh:/install-ollama-models-small.sh
    entrypoint: ["/usr/bin/bash", "/install-ollama-models-small.sh"]
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.11.5
    ports:
      - "6333:6333"
      - "6334:6334"

networks:
  ollama-docker:
    external: false
