name: Java CI

on:
  push:
    branches:
      - main

jobs:
  azure_infrastructure_creation:
    name: 'Create the Azure resources needed for integration tests'
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create Azure resources using Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            $GITHUB_WORKSPACE/src/main/script/deploy-azure-openai-models.sh

  azure_integration_tests:
    name: 'Azure Integration Tests'
    needs:
      - azure_infrastructure_creation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          check-latest: false
          cache: 'maven'
      - name: Run integration tests with Azure
        run: './mvnw package -Dspring.profiles.active=azure'
